using System.Security.Cryptography;
using System.Text;

namespace LiveStreamSound.Shared.Protocol;

/// <summary>
/// Session-level cryptographic primitives that turn the 6-digit session code
/// into a useful authentication + confidentiality boundary on the LAN.
///
/// <para>
/// <b>Why this exists:</b> the 6-digit code is ~20 bits of entropy — fine as
/// a "type this number" UX but useless as a key by itself. We combine it with
/// a server-generated 16-byte nonce (delivered in WELCOME) using HKDF-SHA256
/// to derive a 32-byte AEAD key that's session-specific and cryptographically
/// indistinguishable from random. Audio packets get AES-GCM-encrypted with
/// this key + sequence-number-derived per-packet nonce. WELCOME messages are
/// HMAC-tagged so a client can verify it's talking to the legitimate host
/// (an attacker can't forge a WELCOME without knowing the code).
/// </para>
///
/// <para>
/// <b>Threat model addressed:</b>
/// <list type="bullet">
///   <item>Passive Wireshark capture of audio (F-2) — payloads are encrypted</item>
///   <item>mDNS host spoofing (F-1) — fake host has no key, can't forge WELCOME-MAC</item>
///   <item>UDP audio injection (F-6) — forged packets fail GCM auth tag</item>
///   <item>Invitation MITM (F-3) — invitation now carries an HMAC over its fields</item>
/// </list>
/// </para>
///
/// <para>
/// <b>Wire format change:</b> backwards-incompatible. Existing v1 clients can
/// no longer talk to v2 hosts and vice-versa. Caller MUST bump
/// <see cref="Discovery.DiscoveryConstants.ProtocolVersion"/> when enabling.
/// </para>
/// </summary>
public sealed class SessionCrypto
{
    public const int KeySizeBytes = 32;          // AES-256-GCM
    public const int NonceSizeBytes = 12;        // GCM standard nonce
    public const int TagSizeBytes = 16;          // GCM standard tag
    public const int SaltSizeBytes = 16;

    private readonly byte[] _key;

    private SessionCrypto(byte[] key) { _key = key; }

    /// <summary>
    /// Derive a per-session AES-GCM key from the 6-digit session code and a
    /// server-generated salt. Both sides do the same computation given the
    /// same inputs. Salt MUST be unpredictable (random) and unique per session.
    /// </summary>
    public static SessionCrypto Derive(string sessionCode, ReadOnlySpan<byte> salt)
    {
        if (string.IsNullOrEmpty(sessionCode))
            throw new ArgumentException("Session code required", nameof(sessionCode));
        if (salt.Length < 8)
            throw new ArgumentException("Salt must be at least 8 bytes", nameof(salt));

        var ikm = Encoding.UTF8.GetBytes(sessionCode);
        var info = "LSS-v2-session-key"u8.ToArray();
        var key = new byte[KeySizeBytes];
        HKDF.DeriveKey(HashAlgorithmName.SHA256, ikm, key, salt, info);
        return new SessionCrypto(key);
    }

    /// <summary>Random session salt. Generated by the host on session-start, sent in WELCOME.</summary>
    public static byte[] GenerateSalt()
    {
        var salt = new byte[SaltSizeBytes];
        RandomNumberGenerator.Fill(salt);
        return salt;
    }

    /// <summary>
    /// AES-GCM encrypt audio payload. Per-packet nonce derived from the audio
    /// sequence number (deterministic, never repeats within a session because
    /// sequence is monotonic uint32 + we'd never run a session 2^32 / 50 fps =
    /// ~2.7 years long). The nonce-derivation key is separate from the
    /// payload-encryption key in spirit but here we just use sequence + a
    /// fixed prefix → plaintext nonce, which is FINE for GCM as long as it's
    /// unique per (key, message); duplicates would catastrophically break it.
    /// </summary>
    public void EncryptAudio(uint sequence, ReadOnlySpan<byte> plaintext, Span<byte> ciphertext, Span<byte> tag)
    {
        Span<byte> nonce = stackalloc byte[NonceSizeBytes];
        // 12-byte nonce: 8 bytes "LSS-AUD\0" + 4 bytes big-endian sequence.
        nonce[0] = (byte)'L'; nonce[1] = (byte)'S'; nonce[2] = (byte)'S';
        nonce[3] = (byte)'-'; nonce[4] = (byte)'A'; nonce[5] = (byte)'U';
        nonce[6] = (byte)'D'; nonce[7] = 0;
        nonce[8] = (byte)(sequence >> 24);
        nonce[9] = (byte)(sequence >> 16);
        nonce[10] = (byte)(sequence >> 8);
        nonce[11] = (byte)sequence;

        using var aes = new AesGcm(_key, TagSizeBytes);
        aes.Encrypt(nonce, plaintext, ciphertext, tag);
    }

    /// <summary>
    /// Decrypt + auth-verify an audio payload. Throws <see cref="CryptographicException"/>
    /// on tag mismatch (forged or corrupted packet). Caller should drop the packet
    /// silently — never log the tag-mismatch detail (CWE-209-style info leak).
    /// </summary>
    public void DecryptAudio(uint sequence, ReadOnlySpan<byte> ciphertext, ReadOnlySpan<byte> tag, Span<byte> plaintext)
    {
        Span<byte> nonce = stackalloc byte[NonceSizeBytes];
        nonce[0] = (byte)'L'; nonce[1] = (byte)'S'; nonce[2] = (byte)'S';
        nonce[3] = (byte)'-'; nonce[4] = (byte)'A'; nonce[5] = (byte)'U';
        nonce[6] = (byte)'D'; nonce[7] = 0;
        nonce[8] = (byte)(sequence >> 24);
        nonce[9] = (byte)(sequence >> 16);
        nonce[10] = (byte)(sequence >> 8);
        nonce[11] = (byte)sequence;

        using var aes = new AesGcm(_key, TagSizeBytes);
        aes.Decrypt(nonce, ciphertext, tag, plaintext);
    }

    /// <summary>
    /// HMAC-SHA256 over arbitrary bytes (used for Welcome / Invitation
    /// authentication). Output truncated to 16 bytes — enough authenticity
    /// for a LAN-only protocol and keeps the wire footprint small.
    /// </summary>
    public byte[] Mac(ReadOnlySpan<byte> data)
    {
        var subkey = new byte[32];
        HKDF.DeriveKey(HashAlgorithmName.SHA256, _key, subkey, salt: null,
            info: "LSS-v2-mac"u8.ToArray());
        var full = HMACSHA256.HashData(subkey, data);
        var truncated = new byte[16];
        Buffer.BlockCopy(full, 0, truncated, 0, 16);
        return truncated;
    }

    /// <summary>Constant-time comparison so a MAC verifier doesn't leak via timing.</summary>
    public bool VerifyMac(ReadOnlySpan<byte> data, ReadOnlySpan<byte> tag)
    {
        var expected = Mac(data);
        return CryptographicOperations.FixedTimeEquals(expected, tag);
    }

    /// <summary>
    /// Canonical byte-encoding of the Welcome message used as MAC input on
    /// both sides. Uses pipe-separated UTF-8 of the fields in fixed order.
    /// </summary>
    public static byte[] CanonicalWelcomeBytes(
        string clientId, int audioUdpPort, int sampleRate, int channels,
        string audioCodec, long serverTimeMs, string sessionSaltHex)
    {
        var canonical = $"{clientId}|{audioUdpPort}|{sampleRate}|{channels}|" +
                        $"{audioCodec}|{serverTimeMs}|{sessionSaltHex}";
        return Encoding.UTF8.GetBytes(canonical);
    }

    /// <summary>Lower-case hex string of the bytes (no separator, no prefix).</summary>
    public static string ToHex(ReadOnlySpan<byte> bytes) => Convert.ToHexString(bytes).ToLowerInvariant();

    /// <summary>Parse a hex string back to bytes. Returns null on malformed input.</summary>
    public static byte[]? FromHex(string? hex)
    {
        if (string.IsNullOrEmpty(hex) || hex.Length % 2 != 0) return null;
        try { return Convert.FromHexString(hex); }
        catch { return null; }
    }
}
